version: '2'
services:
  flask:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
        - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/db"
      S3_BUCKET: "put-your-s3-bucket-key-here"
      S3_ACCESS_KEY_ID: "put-your-aws-access-key-id-here"
      S3_SECRET_ACCESS_KEY: "put-your-aws-secret-access-key-id-here"
      AWS_REGION_NAME: "put-your-service-region-name-here"
    volumes:
      - ./server/instapic:/app/instapic
  postgres:
    image: postgres:11.3
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
