FROM python:3.7
LABEL maintainer="mileswonghowing@gmail.com"

ENV FLASK_ENV=development

COPY requirements.txt /requirements.txt
RUN pip install -r requirements.txt

ARG FLASK_HOME=/app
RUN mkdir /uploads

WORKDIR ${FLASK_HOME}


CMD gunicorn -w 4 -b 0.0.0.0:8000 "instapic.app:create_app()"
